### ISSUE TITLE
Interactivity numbers

### ISSUE THREAD

**Issue by addyosmani** [ebidel/lighthouse-httparchive#1]
Any chance we can get consistently interactive on https://lighthouse-viewer.appspot.com/? :)

**Comment by ebidel** [comment]
I can add a few individual metrics. Any others you want to see?

**Comment by addyosmani** [comment]
Maybe firstInteractive too? Could be interesting to see how close they are ❤️

**Comment by ebidel** [comment]
Fixed in https://github.com/ebidel/lighthouse-httparchive/commit/aeed1a207b1c3022d08aecb13ba969ae23b5911a

**Comment by addyosmani** [comment]
🎉 !
